name: Build UCC PWA APK

on:
  workflow_dispatch:

jobs:
  build-pwa-apk:
    runs-on: ubuntu-latest
    steps:
      # Checkout your repo
      - name: Checkout repo
        uses: actions/checkout@v3

      # Install PWA Builder CLI
      - name: Install PWA Builder CLI
        run: |
          npm install -g @pwabuilder/cli

      # Build PWA into APK
      - name: Build PWA APK
        run: |
          pwa build ./UCC --icon=https://raw.githubusercontent.com/justdev-chris/P2E/main/app.ico --platform=android

      # Upload the APK as artifact
      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: UCC-APK
          path: ./dist/android/*.apk