name: Build PWA to APK

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-apk:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      - name: Install PWABuilder CLI
        run: npm install -g @pwabuilder/cli

      - name: Build APK
        run: |
         npx @pwabuilder/cli https://catsdevs.online/Ultimate-Cat-Clicker/UCC/ \
            --output ./build \
            --icon https://raw.githubusercontent.com/justdev-chris/P2E/refs/heads/main/app.ico

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: UCC-APK
          path: build/*.apk
